#!/usr/bin/env bash
# ============================================================================
# validate.sh — End-to-end PRD validation for pi-mulligan
# ----------------------------------------------------------------------------
# This script validates the codebase against the PRD's "Bug Fix Requirements"
# (7 behavioral bugs: BUG-001..BUG-007) and exercises complete user workflows.
#
# Phases (only phases that exist in this codebase are included):
#   1. Type checking        — `tsc --noEmit` (strict)
#   2. Unit / integration    — `vitest run` (the full deterministic suite)
#   3. Integration smoke     — `npm run smoke` (real-pi end-to-end scenarios)
#   4. PRD probe (NEW)       — an INDEPENDENT vitest file that reproduces the
#                              exact "Steps to Reproduce" for BUG-001..BUG-007,
#                              materialized on the fly and cleaned up afterward.
#
# The script exits non-zero if ANY phase fails. It writes no source changes.
# ============================================================================

set -u
cd "$(dirname "$0")"

PASS=0
FAIL=0
probe_file=""
cleanup_done=0

phase() { printf '\n\033[1;34m══════ %s ══════\033[0m\n' "$*"; }
ok()    { printf '\033[1;32m  ✓ PASS\033[0m  %s\n' "$*"; PASS=$((PASS+1)); }
no()    { printf '\033[1;31m  ✗ FAIL\033[0m  %s\n' "$*"; FAIL=$((FAIL+1)); }

cleanup() {
  [ "$cleanup_done" = 1 ] && return 0
  cleanup_done=1
  # Remove the temporary independent probe (never leave repo artifacts).
  [ -n "$probe_file" ] && [ -f "$probe_file" ] && rm -f "$probe_file"
}
trap cleanup EXIT INT TERM

# ----------------------------------------------------------------------------
phase "Phase 1: Type checking (tsc --noEmit, strict)"
# ----------------------------------------------------------------------------
if npm run --silent typecheck > /tmp/mulligan-validate-tsc.log 2>&1; then
  ok "tsc --noEmit clean (0 errors)"
else
  no "tsc --noEmit reported errors:"
  tail -n 25 /tmp/mulligan-validate-tsc.log | sed 's/^/      | /'
fi

# ----------------------------------------------------------------------------
phase "Phase 2: Unit + integration test suite (vitest run)"
# ----------------------------------------------------------------------------
if npm run --silent test > /tmp/mulligan-validate-vitest.log 2>&1; then
  tail -n 4 /tmp/mulligan-validate-vitest.log | sed 's/^/      | /'
  ok "full vitest suite green"
else
  no "vitest suite reported failures:"
  grep -E "FAIL|failed|Tests " /tmp/mulligan-validate-vitest.log | tail -n 25 | sed 's/^/      | /'
fi

# ----------------------------------------------------------------------------
phase "Phase 3: Integration smoke harness (npm run smoke — real pi scenarios)"
# ----------------------------------------------------------------------------
# This spawns a real `pi` process per scenario. It is skipped (not failed) if the
# `pi` binary is unavailable in the current environment, since that is an
# environment limitation rather than a code defect.
if command -v pi >/dev/null 2>&1; then
  if timeout 300 npm run --silent smoke > /tmp/mulligan-validate-smoke.log 2>&1; then
    if grep -q "scenarios passed" /tmp/mulligan-validate-smoke.log; then
      grep -E "PASS |scenarios passed" /tmp/mulligan-validate-smoke.log | tail -n 16 | sed 's/^/      | /'
      ok "integration smoke harness green"
    else
      no "smoke harness did not report a passing summary"
      tail -n 30 /tmp/mulligan-validate-smoke.log | sed 's/^/      | /'
    fi
  else
    no "smoke harness exited non-zero (or timed out)"
    tail -n 30 /tmp/mulligan-validate-smoke.log | sed 's/^/      | /'
  fi
else
  printf '  ! SKIP  pi binary not on PATH (environment limitation; deterministic suite above is authoritative)\n'
fi

# ----------------------------------------------------------------------------
phase "Phase 4: Independent PRD probe (BUG-001..BUG-007 reproduction)"
# ----------------------------------------------------------------------------
# An INDEPENDENT vitest file (not part of the shipped suite) that reproduces the
# EXACT "Steps to Reproduce" from the PRD for each of the seven bugs. It imports
# the REAL source modules. Materialized to test/, run, then deleted by the trap.
probe_file="test/_prd_probe.test.ts"
cat > "$probe_file" <<'PROBE_EOF'
/* Auto-generated by validate.sh — independent PRD reproduction probe. Deleted after the run. */
import { describe, it, expect, beforeEach, afterEach } from "vitest";
import { setConfig, getConfig, type MulliganConfig } from "../src/config.js";
import { clearAll, getRuntime } from "../src/runtime.js";
import { shouldNudge, suppressCheck, bloatReminderHandler, turnEndMetricHandler } from "../src/nudges.js";
import { resolvePinnedHide } from "../src/transforms.js";
import { makeRewindTool } from "../src/tools/rewind.js";
import { makeCancelTool } from "../src/tools/cancel.js";
import { makeCheckpointTool } from "../src/tools/checkpoint.js";
import type { TurnMetric, ShrinkMarker } from "../src/markers.js";
import type { ExtensionAPI, ExtensionContext, AgentToolResult } from "@earendil-works/pi-coding-agent";

beforeEach(() => { clearAll(); setConfig(undefined); });
afterEach(() => { clearAll(); setConfig(undefined); });

function metric(o: Partial<TurnMetric>): TurnMetric {
  return { schema:"pi-mulligan", v:1, kind:"turn-metric", seq:1, ts:1, deltaTokens:5000,
    bloatHit:false, bloatHits:[], grewOverThreshold:true, turnIndex:1, ...o } as TurnMetric;
}
function shrinkM(ts: number): ShrinkMarker {
  return { schema:"pi-mulligan", v:1, kind:"shrink", id:"s1", target:{by_tool_call_id:"c"}, seq:1,
    note:{} as never, ledger:{} as never, ts } as unknown as ShrinkMarker;
}

describe("BUG-001: turn-boundary suppress (no 10-min blackout)", () => {
  it("marker from the PREVIOUS turn does NOT suppress a later turn", () => {
    const T = 1_000_000;
    const latest = metric({ ts: T + 120_000, seq: 3 });
    const prev = metric({ ts: T, seq: 2 });
    expect(suppressCheck(latest, [latest, prev], { rewinds: [], shrinks: [shrinkM(T)] })).toBe(false);
  });
  it("marker created DURING this turn DOES suppress (positive control)", () => {
    const latest = metric({ ts: 200, seq: 3 }), prev = metric({ ts: 100, seq: 2 });
    expect(suppressCheck(latest, [latest, prev], { rewinds: [], shrinks: [shrinkM(150)] })).toBe(true);
  });
});

describe("BUG-002: resolvePinnedHide compaction-aware", () => {
  it("retained-tail pinned entries resolve after a compaction (was [] before fix)", () => {
    const messages = [
      { role: "user" },
      { role: "user", content: "compactionSummary" },
      { role: "assistant", content: [{ type:"toolCall", id:"X", name:"read", arguments:{} }] },
      { role: "toolResult", toolCallId:"X", content:"BIG" },
    ];
    const branch = [
      { type:"message", id:"e1" }, { type:"compaction", id:"c1" },
      { type:"message", id:"e3" }, { type:"message", id:"e4" },
    ];
    expect(resolvePinnedHide(messages as never, branch as never, ["e3","e4"])).toEqual([2,3]);
  });
  it("compact-away-head pinned entry correctly no-ops", () => {
    const messages = [{ role:"user", content:"summary" }, { role:"assistant" }];
    const branch = [{ type:"message", id:"e1" }, { type:"compaction", id:"c1" }, { type:"message", id:"e3" }];
    expect(resolvePinnedHide(messages as never, branch as never, ["e1"])).toEqual([]);
  });
});

describe("BUG-003: spec §5.1 criterion (b) three ~4k turns fire", () => {
  it("moving-average 4000 >= default threshold 4000 → fires", () => {
    const cfg: MulliganConfig = getConfig();
    expect(cfg.nudges.driftThresholdTokens).toBe(4000);
    const m3 = [metric({deltaTokens:4000,seq:3}), metric({deltaTokens:4000,seq:2}), metric({deltaTokens:4000,seq:1})];
    expect(shouldNudge(m3, cfg)).toBe(true);
  });
  it("criterion (a) single 8k amid small does NOT fire", () => {
    expect(shouldNudge([metric({deltaTokens:8000,seq:3}), metric({deltaTokens:500,seq:2}), metric({deltaTokens:500,seq:1})], getConfig())).toBe(false);
  });
});

describe("BUG-004: no pendingBloatHits leak when perTurnDrift off", () => {
  it("turn_end clears the accumulator even when perTurnDrift=false", () => {
    setConfig({ enabled:true, nudges:{ bloatReminder:true, perTurnDrift:false } } as never);
    const rt = getRuntime("s4");
    const fakeCtx = { sessionManager:{ getSessionId:()=>"s4", getContextUsage:()=>({}) } } as never as ExtensionContext;
    const ev = { type:"turn_end", turnIndex:1, message:{}, toolResults:[] } as never;
    bloatReminderHandler({ content:[{type:"text",text:"x".repeat(20000)}], toolName:"bash", toolCallId:"c1", input:{}, isError:false } as never, fakeCtx);
    bloatReminderHandler({ content:[{type:"text",text:"y".repeat(20000)}], toolName:"bash", toolCallId:"c2", input:{}, isError:false } as never, fakeCtx);
    expect(rt.pendingBloatHits.length).toBe(2);
    turnEndMetricHandler({} as never, ev, fakeCtx);
    expect(rt.pendingBloatHits.length).toBe(0);
  });
});

function fakePi() {
  const appended: {customType:string;data:unknown}[] = [];
  const labels: {id:string;label:string|undefined}[] = [];
  return { appended, labels, pi: {
    appendEntry(ct:string, d?:unknown){ appended.push({customType:ct,data:d}); return `leaf-${appended.length}`; },
    sendMessage(){}, setLabel(id:string,l:string|undefined){ labels.push({id,label:l}); },
  } as unknown as ExtensionAPI };
}
function fakeCtx(entries: unknown[]) {
  return { sessionManager: {
    getSessionId:()=>"s5", getLeafId:()=>"leaf-1", getEntries:()=>entries, getBranch:()=>entries,
    buildContextEntries:()=>entries, getLabel:()=>undefined,
  } } as unknown as ExtensionContext;
}
function txt(r: AgentToolResult<unknown>): string { return (r.content[0] as {text:string}).text; }

describe("BUG-005: retry budget excludes cancelled rewinds", () => {
  it("cancelled rewind does NOT consume budget (3rd rewind allowed)", async () => {
    setConfig({ enabled:true, rewind:{ maxRetriesPerPrompt:2, maxDepth:50, abortContextFraction:0.9,
      requireMutationWarning:false, protectedRoles:["first:user","latest:user"], enabled:true } } as never);
    const { pi } = fakePi();
    const entries = [
      { type:"message", id:"u1", message:{ role:"user", content:"do the task" } },
      { type:"custom", customType:"mulligan:rewind", data:{ kind:"rewind", id:"rw1", seq:1 } },
      { type:"custom", customType:"mulligan:note", data:{} },
      { type:"custom", customType:"mulligan:cancel", data:{ kind:"cancel", targetId:"rw1" } },
      { type:"custom", customType:"mulligan:rewind", data:{ kind:"rewind", id:"rw2", seq:2 } },
    ];
    const tool = makeRewindTool(pi);
    const note = { what_happened:"w", true_current_state:"s", next:"n" };
    const res = await tool.execute("call-1", { note, granularity:"last_turn" } as never, undefined, undefined, fakeCtx(entries));
    expect(txt(res)).not.toContain("retry budget");
    expect(txt(res)).toContain("rewound");
  });
});

describe("BUG-006: cancel not-found text path-specific", () => {
  it("target path → 'for that target'", async () => {
    const { pi } = fakePi();
    const ctx = fakeCtx([{ type:"message", id:"u1", message:{ role:"user", content:"hi" } }]);
    const tool = makeCancelTool(pi);
    const res = await tool.execute("c", { target:{ by_tool_name:"read", occurrence:"last" } } as never, undefined, undefined, ctx);
    expect(txt(res)).toBe("Mulligan: no active marker found for that target — nothing to cancel.");
  });
  it("markerId path → 'with that id'", async () => {
    const { pi } = fakePi();
    const ctx = fakeCtx([{ type:"message", id:"u1", message:{ role:"user", content:"hi" } }]);
    const tool = makeCancelTool(pi);
    const res = await tool.execute("c", { markerId:"nope" } as never, undefined, undefined, ctx);
    expect(txt(res)).toBe("Mulligan: no active marker found with that id — nothing to cancel.");
  });
});

describe("BUG-007: checkpoint gated by config.enabled (E14)", () => {
  it("disabled → refuses 'Mulligan is disabled.' and writes NO label", async () => {
    setConfig({ enabled:false } as never);
    const { pi, labels } = fakePi();
    const ctx = fakeCtx([{ type:"message", id:"u1", message:{ role:"user", content:"hi" } }]);
    const tool = makeCheckpointTool(pi);
    const res = await tool.execute("c", { name:"before-x" } as never, undefined, undefined, ctx);
    expect(txt(res)).toBe("Mulligan: refused — Mulligan is disabled.");
    expect(labels.length).toBe(0);
  });
});

describe("E2E: pinned rewind survives compaction through filterPipeline", () => {
  it("retained-tail tool result stays hidden after compaction; pairing preserved", async () => {
    const { filterPipeline } = await import("../src/transforms.js");
    const messages = [
      { role:"user", content:"original task" },
      { role:"user", content:"compactionSummary placeholder" },
      { role:"assistant", content:[{ type:"toolCall", id:"bigRead", name:"read", arguments:{} }] },
      { role:"toolResult", toolCallId:"bigRead", content:"HUGE_BLOAT_38k_tokens" },
    ];
    const branch = [{ type:"message", id:"e0" }, { type:"compaction", id:"c1" },
      { type:"message", id:"e2" }, { type:"message", id:"e3" }];
    const markers = { rewinds:[{ schema:"pi-mulligan", v:1, kind:"rewind", id:"rw1",
      granularity:"last_tool_call_group", options:{}, excludeToolCallId:"rw1", seq:1,
      hideEntryIds:["e2","e3"], note:{}, ledger:{readFiles:[],modifiedFiles:[],bashSideEffects:[]} }],
      shrinks:[], metric:null, cancelledIds:[], recentMetrics:[] };
    const out = filterPipeline(messages as never, markers as never, undefined, branch as never);
    expect(JSON.stringify(out)).not.toContain("HUGE_BLOAT_38k_tokens");
    expect(out.some((m:any)=>Array.isArray(m.content)&&m.content.some((b:any)=>b.type==="toolCall"))).toBe(false);
  });
});
PROBE_EOF

if npx vitest run "$probe_file" > /tmp/mulligan-validate-probe.log 2>&1; then
  grep -E "Tests " /tmp/mulligan-validate-probe.log | tail -n 1 | sed 's/^/      | /'
  ok "independent PRD probe (BUG-001..BUG-007 + E2E compaction) green"
else
  no "independent PRD probe reported failures:"
  grep -E "FAIL |✓|✗|×|Error|expected|Tests " /tmp/mulligan-validate-probe.log | tail -n 30 | sed 's/^/      | /'
fi

# ----------------------------------------------------------------------------
phase "VALIDATION SUMMARY"
# ----------------------------------------------------------------------------
total=$((PASS+FAIL))
printf '\n  Phases passed: %d/%d   Phases failed: %d\n' "$PASS" "$total" "$FAIL"
if [ "$FAIL" -eq 0 ]; then
  printf '\n  \033[1;32m✅ ALL VALIDATION PHASES PASSED — no issues found.\033[0m\n\n'
  exit 0
else
  printf '\n  \033[1;31m❌ VALIDATION FAILED — %d phase(s) reported issues.\033[0m\n\n' "$FAIL"
  exit 1
fi